const testCases = [
  {
    name: "苗字の空白エラーチェック",
    lastNameInput: "",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "last_name",
    expectedMessage: "苗字を入力してください",
  },
  {
    name: "名前の空白エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "first_name",
    expectedMessage: "名前を入力してください",
  },
  {
    name: "苗字（カナ）の空白エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "",
    firstNameKanaInput: "テスト",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "last_name_kana",
    expectedMessage: "苗字(カナ)を入力してください",
  },
  {
    name: "名前（カナ）の空白エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "first_name_kana",
    expectedMessage: "名前(カナ)を入力してください",
  },
  {
    name: "苗字の30文字以上エラーチェック",
    lastNameInput:
      "テストテストテストテストテストテストテストテストテストテスト太郎",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "last_name",
    expectedMessage: "苗字は30文字以内で入力してください",
  },
  {
    name: "名前の30文字以上エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テストテストテストテストテストテストテストテストテストテスト太郎",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "first_name",
    expectedMessage: "名前は30文字以内で入力してください",
  },
  {
    name: "苗字（カナ）の15文字以上エラーチェック",
    lastNameInput:"テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テストテストテストテストテスト太郎",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "last_name_kana",
    expectedMessage: "苗字(カナ)は15文字以内で入力してください",
  },
  {
    name: "名前（カナ）の15文字以上エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テストテストテストテストテスト太郎",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "first_name_kana",
    expectedMessage: "名前(カナ)は15文字以内で入力してください",
  },
  {
    name: "苗字（カナ）のカタカナエラーチェック",
    lastNameInput:"テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テストテスト太郎",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "last_name_kana",
    expectedMessage: "苗字(カナ)はカタカナのみで入力してください",
  },
  {
    name: "名前(カナ)のカタカナエラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テストテスト太郎",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "first_name_kana",
    expectedMessage: "名前(カナ)はカタカナのみで入力してください",
  },  
  {
    name: "生年月日(月)の空白エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "birth_month",
    expectedMessage: "生年月日(月)を選択してください",
  },
  {
    name: "生年月日(日)の空白エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "birth_day",
    expectedMessage: "生年月日(日)を選択してください",
  },
  {
    name: "性別の空白エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "sex_id",
    expectedMessage: "性別を選択してください",
  },
  {
    name: "電話番号の空白エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "portable_tel",
    expectedMessage: "電話番号を入力してください",
  },
  {
    name: "電話番号の10文字未満エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "080123",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "portable_tel",
    expectedMessage:
      "電話番号は10文字以上・11文字以内の半角数字・ハイフンなしで入力してください",
  },
  {
    name: "電話番号の11文字以上エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "0801234567890",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "portable_tel",
    expectedMessage:
      "電話番号は10文字以上・11文字以内の半角数字・ハイフンなしで入力してください",
  },
  {
    name: "メールアドレスの空白エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "portable_email",
    expectedMessage: "メールアドレスを入力してください",
  },
  {
    name: "メールアドレスの形式エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mzmynavi.jp",
    emailRe: "kaihara.ryuju.mzmynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "portable_email",
    expectedMessage: "メールアドレスの形式で入力してください",
  },
  {
    name: "メールアドレスの50文字以上エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email:
      "kaihara.ryuju.mzkaihara.ryuju.mzkaihara.ryuju.mzkaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "portable_email",
    expectedMessage: "メールアドレスは50文字以内で入力してください",
  },
  {
    name: "確認用メールアドレスの空白エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "portable_email_re",
    expectedMessage: "確認用メールアドレスを入力してください",
  },
  {
    name: "確認用メールアドレスとメールアドレスが異なるエラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz1@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "portable_email_re",
    expectedMessage: "確認用メールアドレスがメールアドレスと異なります",
  },
  {
    name: "大学名の空白エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "educations_school",
    expectedMessage: "大学名を入力してください",
  },
  {
    name: "大学名の70文字以上エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school:
      "マイナビ大学マイナビ大学マイナビ大学マイナビ大学マイナビ大学マイナビ大学マイナビ大学マイナビ大学マイナビ大学マイナビ大学マイナビ大学マイナビ大学マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "educations_school",
    expectedMessage: "大学名は70文字以内で入力してください",
  },
  {
    name: "競技名の空白エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "sport_name",
    expectedMessage: "競技名を入力してください",
  },
  {
    name: "競技名の50文字以上エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name:
      "バレーボールバレーボールバレーボールバレーボールバレーボールバレーボールバレーボールバレーボールバレーボールバレーボール",
    graduation_year: "卒業済み",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "sport_name",
    expectedMessage: "競技名は50文字以内で入力してください",
  },
  {
    name: "相談内容の2000文字以上エラーチェック",
    lastNameInput: "テスト",
    firstNameInput: "テスト",
    lastNameKanaInput: "テスト",
    firstNameKanaInput: "テスト",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "卒業済み",
    memo: "相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容",
    errorName: "memo",
    expectedMessage: "相談内容は2000文字以内で入力してください",
  },
];
module.exports = { testCases };
