const testCasesStep1 = [
    {
      name: "苗字の空白エラーチェック",
      graduationYear: "",
      errorName: "graduation_year",
      expectedMessage: "卒業年次を選択してください",
    },
];

const testCasesStep2 = [
    {
        name: "競技名の空白エラーチェック",
        sportName: "",
        errorName: "sport_name",
        expectedMessage: "競技名を入力してください",
    },
    {
        name: "競技名の50文字以上エラーチェック",
        sportName: "バレーボールバレーボールバレーボールバレーボールバレーボールバレーボールバレーボールバレーボールバレーボールバレーボール",
        errorName: "sport_name",
        expectedMessage: "競技名は50文字以内で入力してください",
    },
];

const testCasesStep3 = [
    {
        name: "苗字の空白エラーチェック",
        lastNameInput: "",
        firstNameInput: "テスト",
        lastNameKanaInput: "テスト",
        firstNameKanaInput: "テスト",
        birthYear: "1997",
        birthMonth: "10",
        birthDay: "29",
        sex_id: "1",
        errorName: "last_name",
        expectedMessage: "苗字を入力してください",
    },
    {
        name: "名前の空白エラーチェック",
        lastNameInput: "テスト",
        firstNameInput: "",
        lastNameKanaInput: "テスト",
        firstNameKanaInput: "テスト",
        birthYear: "1997",
        birthMonth: "10",
        birthDay: "29",
        sex_id: "1",
        errorName: "first_name",
        expectedMessage: "名前を入力してください",
    },
    {
        name: "苗字(カナ)の空白エラーチェック",
        lastNameInput: "テスト",
        firstNameInput: "テスト",
        lastNameKanaInput: "",
        firstNameKanaInput: "テスト",
        birthYear: "1997",
        birthMonth: "10",
        birthDay: "29",
        sex_id: "1",
        errorName: "last_name_kana",
        expectedMessage: "苗字(カナ)を入力してください",
    },
    {
        name: "名前(カナ)の空白エラーチェック",
        lastNameInput: "テスト",
        firstNameInput: "テスト",
        lastNameKanaInput: "テスト",
        firstNameKanaInput: "",
        birthYear: "1997",
        birthMonth: "10",
        birthDay: "29",
        sex_id: "1",
        errorName: "first_name_kana",
        expectedMessage: "名前(カナ)を入力してください",
    },
    {
        name: "苗字の30文字エラーチェック",
        lastNameInput: "テストテストテストテストテストテストテストテストテストテストテスト",
        firstNameInput: "テスト",
        lastNameKanaInput: "テスト",
        firstNameKanaInput: "テスト",
        birthYear: "1997",
        birthMonth: "10",
        birthDay: "29",
        sex_id: "1",
        errorName: "last_name",
        expectedMessage: "苗字は30文字以内で入力してください",
    },
    {
        name: "名前の30文字エラーチェック",
        lastNameInput: "テスト",
        firstNameInput: "テストテストテストテストテストテストテストテストテストテストテスト",
        lastNameKanaInput: "テスト",
        firstNameKanaInput: "テスト",
        birthYear: "1997",
        birthMonth: "10",
        birthDay: "29",
        sex_id: "1",
        errorName: "first_name",
        expectedMessage: "名前は30文字以内で入力してください",
    },
    {
        name: "苗字(カナ)の15文字エラーチェック",
        lastNameInput: "テスト",
        firstNameInput: "テスト",
        lastNameKanaInput: "テストテストテストテストテスト太郎",
        firstNameKanaInput: "テスト",
        birthYear: "1997",
        birthMonth: "10",
        birthDay: "29",
        sex_id: "1",
        errorName: "last_name_kana",
        expectedMessage: "苗字(カナ)は15文字以内で入力してください",
    },
    {
        name: "名前(カナ)の15文字エラーチェック",
        lastNameInput: "テスト",
        firstNameInput: "テスト",
        lastNameKanaInput: "テスト",
        firstNameKanaInput: "テストテストテストテストテスト太郎",
        birthYear: "1997",
        birthMonth: "10",
        birthDay: "29",
        sex_id: "1",
        errorName: "first_name_kana",
        expectedMessage: "名前(カナ)は15文字以内で入力してください",
    },
    {
        name: "苗字(カナ)のカタカナエラーチェック",
        lastNameInput: "テスト",
        firstNameInput: "テスト",
        lastNameKanaInput: "テスト太郎",
        firstNameKanaInput: "テスト",
        birthYear: "1997",
        birthMonth: "10",
        birthDay: "29",
        sex_id: "1",
        errorName: "last_name_kana",
        expectedMessage: "苗字(カナ)は全角カナで入力してください",
    },
    {
        name: "名前(カナ)のカタカナエラーチェック",
        lastNameInput: "テスト",
        firstNameInput: "テスト",
        lastNameKanaInput: "テスト",
        firstNameKanaInput: "テスト太郎",
        birthYear: "1997",
        birthMonth: "10",
        birthDay: "29",
        sex_id: "1",
        errorName: "first_name_kana",
        expectedMessage: "名前(カナ)は全角カナで入力してください",
    },
    {
        name: "生年月日（日）のエラーチェック",
        lastNameInput: "テスト",
        firstNameInput: "テスト",
        lastNameKanaInput: "テスト",
        firstNameKanaInput: "テスト",
        birthYear: "1997",
        birthMonth: "10",
        birthDay: "",
        sex_id: "1",
        errorName: "birth_date",
        expectedMessage: "生年月日を選択してください",
    },
    {
        name: "生年月日（月）のエラーチェック",
        lastNameInput: "テスト",
        firstNameInput: "テスト",
        lastNameKanaInput: "テスト",
        firstNameKanaInput: "テスト",
        birthYear: "1997",
        birthMonth: "",
        birthDay: "29",
        sex_id: "1",
        errorName: "birth_date",
        expectedMessage: "生年月日を選択してください",
    },
    
]

const testCasesStep4 = [
    {
        name: "電話番号の空白エラーチェック",
        phone: "",
        email: "kaihara.ryuju.mz@mynavi.jp",
        emailRe: "kaihara.ryuju.mz@mynavi.jp",
        errorName: "portable_tel",
        expectedMessage: "電話番号を入力してください",
    },
    {
        name: "電話番号の10文字未満エラーチェック",
        phone: "080123",
        email: "kaihara.ryuju.mz@mynavi.jp",
        emailRe: "kaihara.ryuju.mz@mynavi.jp",
        errorName: "portable_tel",
        expectedMessage: "電話番号は10文字以上・11文字以内で入力してください",
    },
    {
        name: "電話番号の11文字以上エラーチェック",
        phone: "0801234567890",
        email: "kaihara.ryuju.mz@mynavi.jp",
        emailRe: "kaihara.ryuju.mz@mynavi.jp",
        errorName: "portable_tel",
        expectedMessage: "電話番号は10文字以上・11文字以内で入力してください",
    },
    {
        name: "電話番号のハイフンエラーチェック",
        phone: "080-123-567",
        email: "kaihara.ryuju.mz@mynavi.jp",
        emailRe: "kaihara.ryuju.mz@mynavi.jp",
        errorName: "portable_tel",
        expectedMessage: "電話番号は半角数字・ハイフンなしで入力してください",
    },
    {
        name: "メールアドレスの空白エラーチェック",
        phone: "08012356711",
        email: "",
        emailRe: "kaihara.ryuju.mz@mynavi.jp",
        errorName: "portable_email",
        expectedMessage: "メールアドレスを入力してください",
    },
    {
        name: "確認用メールアドレスの空白エラーチェック",
        phone: "08012356711",
        email: "kaihara.ryuju.mz@mynavi.jp",
        emailRe: "",
        errorName: "portable_email_re",
        expectedMessage: "確認用メールアドレスを入力してください",
    },
    {
        name: "メールアドレスの形式エラーチェック",
        phone: "08012356711",
        email: "kaihara.ryuju.mzmynavi.jp",
        emailRe: "kaihara.ryuju.mzmynavi.jp",
        errorName: "portable_email",
        expectedMessage: "メールアドレスの形式で入力してください",
    },
    {
        name: "メールアドレスの50文字以上エラーチェック",
        phone: "08012356711",
        email: "kaihara.ryuju.mzkaihara.ryuju.mzkaihara.ryuju.mzkaihara.ryuju.mz@mynavi.jp",
        emailRe: "",
        errorName: "portable_email",
        expectedMessage: "メールアドレスは50文字以内で入力してください",
    },
    {
        name: "確認用メールアドレスとメールアドレスが異なるエラーチェック",
        phone: "08012356711",
        email: "kaihara.ryuju.mz@mynavi.jp",
        emailRe: "kaihara.ryujumz@mynavi.jp",
        errorName: "portable_email_re",
        expectedMessage: "確認用メールアドレスがメールアドレスと異なります",
    },
];

const testCasesStep5 = [
    {
        name: "当サイトをどう知りましたか？の空白エラーチェック",
        inforMedia: "",
        introducer: "",
        errorName: "infor_media",
        expectedMessage: "当サイトをどう知りましたか？を選択してください",
    },
    {
        name: "友達からの紹介の入力の空白エラーチェック",
        inforMedia: "19",
        introducer: "",
        errorName: "introducer",
        expectedMessage: "ご紹介者の氏名・チーム名を入力してください",
    },
    {
        name: "監督からの紹介の入力の空白エラーチェック",
        inforMedia: "23",
        introducer: "",
        errorName: "introducer",
        expectedMessage: "ご紹介者の氏名・チーム名を入力してください",
    },
    {
        name: "ご紹介の氏名・チーム名の入力の空白エラーチェック",
        inforMedia: "45",
        introducer: "",
        errorName: "introducer",
        expectedMessage: "ご紹介者の氏名・チーム名を入力してください",
    },
    {
        name: "ご紹介の氏名・チーム名の100文字以上エラーチェック",
        inforMedia: "45",
        introducer: "バレーボールバレーボールバレーボールバレーボールバレーボールバレーボールバレーボールバレーボールバレーバレーボールバレーボールバレーボールバレーボールバレーボールバレーボールバレーボールバレーボールバレ",
        errorName: "introducer",
        expectedMessage: "ご紹介者の氏名・チーム名は100文字以内で入力してください",
    },
]



module.exports = { testCasesStep1, testCasesStep2, testCasesStep3, testCasesStep4, testCasesStep5 };