const testCases = [
  {
    name: "名前の空白エラーチェック",
    nameInput: "",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "2025年3月卒業",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "name",
    expectedMessage: "氏名を入力してください",
  },
  {
    name: "名前の50文字以上エラーチェック",
    nameInput:
      "テストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテスト太郎",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "2025年3月卒業",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "name",
    expectedMessage: "氏名は50文字以内で入力してください",
  },
  {
    name: "生年月日(月)の空白エラーチェック",
    nameInput: "テスト太郎",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "2025年3月卒業",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "birth_month",
    expectedMessage: "生年月日(月)を選択してください",
  },
  {
    name: "生年月日(日)の空白エラーチェック",
    nameInput: "テスト太郎",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "2025年3月卒業",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "birth_day",
    expectedMessage: "生年月日(日)を選択してください",
  },
  {
    name: "性別の空白エラーチェック",
    nameInput: "テスト太郎",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "2025年3月卒業",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "sex_id",
    expectedMessage: "性別を選択してください",
  },
  {
    name: "電話番号の空白エラーチェック",
    nameInput: "マイナビ",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "2025年3月卒業",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "portable_tel",
    expectedMessage: "電話番号を入力してください",
  },
  {
    name: "電話番号の10文字未満エラーチェック",
    nameInput: "マイナビ",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "080123",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "2025年3月卒業",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "portable_tel",
    expectedMessage:
      "電話番号は10文字以上・11文字以内の半角数字・ハイフンなしで入力してください",
  },
  {
    name: "電話番号の11文字以上エラーチェック",
    nameInput: "マイナビ",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "0801234567890",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "2025年3月卒業",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "portable_tel",
    expectedMessage:
      "電話番号は10文字以上・11文字以内の半角数字・ハイフンなしで入力してください",
  },
  {
    name: "メールアドレスの空白エラーチェック",
    nameInput: "マイナビ",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "2025年3月卒業",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "portable_email",
    expectedMessage: "メールアドレスを入力してください",
  },
  {
    name: "メールアドレスの形式エラーチェック",
    nameInput: "マイナビ",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mzmynavi.jp",
    emailRe: "kaihara.ryuju.mzmynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "2025年3月卒業",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "portable_email",
    expectedMessage: "メールアドレスの形式で入力してください",
  },
  {
    name: "メールアドレスの256文字以上エラーチェック",
    nameInput: "マイナビ",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email:
      "kaihara.ryuju.mzkaihara.ryuju.mzkaihara.ryuju.mzkaihara.ryuju.mzkaihara.ryuju.mzkaihara.ryuju.mzkaihara.ryuju.mzkaihara.ryuju.mzkaihara.ryuju.mzkaihara.ryuju.mzkaihara.ryuju.mzkaihara.ryuju.mzkaihara.ryuju.mzkaihara.ryuju.mzkaihara.ryuju.mzkaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "2025年3月卒業",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "portable_email",
    expectedMessage: "メールアドレスは256文字以内で入力してください",
  },
  {
    name: "確認用メールアドレスの空白エラーチェック",
    nameInput: "マイナビ",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "2025年3月卒業",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "portable_email_re",
    expectedMessage: "確認用メールアドレスを入力してください",
  },
  {
    name: "確認用メールアドレスとメールアドレスが異なるエラーチェック",
    nameInput: "マイナビ",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz1@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "2025年3月卒業",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "portable_email_re",
    expectedMessage: "確認用メールアドレスがメールアドレスと異なります",
  },
  {
    name: "大学名の空白エラーチェック",
    nameInput: "マイナビ",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "",
    sport_name: "バレーボール",
    graduation_year: "2025年3月卒業",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "educations_school",
    expectedMessage: "大学名を入力してください",
  },
  {
    name: "大学名の50文字以上エラーチェック",
    nameInput: "マイナビ",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school:
      "マイナビマイナビマイナビマイナビマイナビマイナビマイナビマイナビマイナビマイナビマイナビマイナビマイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "2025年3月卒業",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "educations_school",
    expectedMessage: "大学名は50文字以内で入力してください",
  },
  {
    name: "競技名の空白エラーチェック",
    nameInput: "マイナビ",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "",
    graduation_year: "2025年3月卒業",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "sport_name",
    expectedMessage: "競技名を入力してください",
  },
  {
    name: "競技名の50文字以上エラーチェック",
    nameInput: "マイナビ",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name:
      "バレーボールバレーボールバレーボールバレーボールバレーボールバレーボールバレーボールバレーボールバレーボールバレーボール",
    graduation_year: "2025年3月卒業",
    memo: "2019年マイナビ大会で優勝しました。",
    errorName: "sport_name",
    expectedMessage: "競技名は50文字以内で入力してください",
  },
  {
    name: "相談内容の2000文字以上エラーチェック",
    nameInput: "マイナビ",
    kana: "マイナビ",
    birthYear: "1997",
    birthMonth: "10",
    birthDay: "29",
    sex_id: "1",
    address: "マイナビ区",
    phone: "08012345678",
    email: "kaihara.ryuju.mz@mynavi.jp",
    emailRe: "kaihara.ryuju.mz@mynavi.jp",
    educations_school: "マイナビ大学",
    sport_name: "バレーボール",
    graduation_year: "2025年3月卒業",
    memo: "相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容相談内容",
    errorName: "memo",
    expectedMessage: "相談内容は2000文字以内で入力してください",
  },
];
module.exports = { testCases };
